# Generated by Django 5.1.6 on 2025-07-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('common_denonyms', models.JSONField(blank=True, default=list, help_text='List of common denonyms')),
                ('weight_to_volume_conversion', models.FloatField(default=1.0, help_text='Grams per milliliter (g/ml)')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('servings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('liter', 'liter'), ('dl', 'deciliter'), ('cl', 'centiliter'), ('ml', 'milliliter'), ('krm', 'kryddmått'), ('tsk', 'tesked'), ('msk', 'matsked'), ('st', 'styck'), ('nypa', 'nypa'), ('klyfta', 'klyfta')], max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipes.managedingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
