# Generated by Django 5.2.4 on 2025-08-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('l', 'liter'), ('dl', 'deciliter'), ('cl', 'centiliter'), ('ml', 'milliliter'), ('krm', 'kryddmått'), ('tsk', 'tesked'), ('msk', 'matsked'), ('st', 'styck')], max_length=50),
        ),
    ]
