# Generated by Django 4.2.23 on 2025-07-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('liter', 'liter'), ('dl', 'deciliter'), ('cl', 'centiliter'), ('ml', 'milliliter'), ('krm', 'kryddmått'), ('tsk', 'tesked'), ('msk', 'matsked')], max_length=50),
        ),
    ]
