# Generated by Django 5.1.6 on 2025-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedingredient',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='managedingredient',
            name='common_denonyms',
            field=models.JSONField(blank=True, default=list, help_text='List of common denonyms'),
        ),
        migrations.AddField(
            model_name='managedingredient',
            name='container_sizes',
            field=models.JSONField(blank=True, default=list, help_text='List of common container sizes in grams or ml'),
        ),
        migrations.AddField(
            model_name='managedingredient',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='managedingredient',
            name='weight_to_volume_conversion',
            field=models.FloatField(blank=True, help_text='Grams per milliliter (g/ml)', null=True),
        ),
    ]
