# Generated by Django 5.0.7 on 2025-07-30 12:00

from django.db import migrations

def preload_ingredients(apps, schema_editor):
    ManagedIngredient = apps.get_model('recipes', 'ManagedIngredient')
    
    ingredients_to_add = [

        # NOTE: Weight to volume is done by chatgpt and is probably wildly inaccurate.
        # Categories:
        # - Skafferi
        # - Mejeri
        # - Frukt & Grönt
        # - Protein
        # - Kryddor 
        # - Övrigt  

        
        # Skafferi
        {'name': 'Vetemjöl', 'category': 'Skafferi', 'common_denonyms': ['mjöl'], 'weight_to_volume_conversion': 0.53},
        {'name': 'Strösocker', 'category': 'Skafferi', 'common_denonyms': ['socker'], 'weight_to_volume_conversion': 0.85},
        {'name': 'Farinsocker', 'category': 'Skafferi', 'weight_to_volume_conversion': 0.95},
        {'name': 'Bakpulver', 'category': 'Skafferi', 'weight_to_volume_conversion': 1.0},
        {'name': 'Bikarbonat', 'category': 'Skafferi', 'weight_to_volume_conversion': 1.0},
        {'name': 'Salt', 'category': 'Skafferi', 'common_denonyms': ['bordssalt'], 'weight_to_volume_conversion': 1.2},
        {'name': 'Svartpeppar', 'category': 'Skafferi', 'common_denonyms': ['pepparkorn'], 'weight_to_volume_conversion': 0.5},
        {'name': 'Olivolja', 'category': 'Skafferi', 'weight_to_volume_conversion': 0.92},
        {'name': 'Matolja', 'category': 'Skafferi', 'common_denonyms': ['olja'], 'weight_to_volume_conversion': 0.92},
        {'name': 'Pasta', 'category': 'Skafferi', 'weight_to_volume_conversion': 0.6},
        {'name': 'Ris', 'category': 'Skafferi', 'weight_to_volume_conversion': 0.85},
        {'name': 'Krossade tomater', 'category': 'Skafferi', 'weight_to_volume_conversion': 1.0},
        {'name': 'Kycklingbuljong', 'category': 'Skafferi', 'common_denonyms': ['kycklingfond'], 'weight_to_volume_conversion': 1.0},
        {'name': 'Grönsaksbuljong', 'category': 'Skafferi', 'common_denonyms': ['grönsaksfond'], 'weight_to_volume_conversion': 1.0},
        
        # Mejeri
        {'name': 'Mjölk', 'category': 'Mejeri', 'weight_to_volume_conversion': 1.04},
        {'name': 'Smör', 'category': 'Mejeri', 'weight_to_volume_conversion': 0.91},
        {'name': 'Ägg', 'category': 'Mejeri', 'common_denonyms': ['ägg'], 'weight_to_volume_conversion': 1.0},
        {'name': 'Riven cheddar', 'category': 'Mejeri', 'weight_to_volume_conversion': 0.5},
        {'name': 'Mozzarella', 'category': 'Mejeri', 'weight_to_volume_conversion': 0.6},
        {'name': 'Yoghurt', 'category': 'Mejeri', 'weight_to_volume_conversion': 1.0},
        
        # Frukt & Grönt
        {'name': 'Lök', 'category': 'Frukt & Grönt', 'weight_to_volume_conversion': 0.5},
        {'name': 'Vitlök', 'category': 'Frukt & Grönt', 'common_denonyms': ['vitlöksklyfta'], 'weight_to_volume_conversion': 0.7},
        {'name': 'Morötter', 'category': 'Frukt & Grönt', 'common_denonyms': ['morot'], 'weight_to_volume_conversion': 0.6},
        {'name': 'Selleri', 'category': 'Frukt & Grönt', 'common_denonyms': ['selleristjälk'], 'weight_to_volume_conversion': 0.5},
        {'name': 'Potatis', 'category': 'Frukt & Grönt', 'common_denonyms': ['potatis'], 'weight_to_volume_conversion': 0.8},
        {'name': 'Tomater', 'category': 'Frukt & Grönt', 'common_denonyms': ['tomat'], 'weight_to_volume_conversion': 0.6},
        {'name': 'Sallad', 'category': 'Frukt & Grönt', 'weight_to_volume_conversion': 0.2},
        {'name': 'Citron', 'category': 'Frukt & Grönt', 'weight_to_volume_conversion': 1.0},
        {'name': 'Äpplen', 'category': 'Frukt & Grönt', 'common_denonyms': ['äpple'], 'weight_to_volume_conversion': 0.7},
        {'name': 'Bananer', 'category': 'Frukt & Grönt', 'common_denonyms': ['banan'], 'weight_to_volume_conversion': 0.7},

        # Protein
        {'name': 'Kycklingfilé', 'category': 'Protein', 'weight_to_volume_conversion': 1.0},
        {'name': 'Nötfärs', 'category': 'Protein', 'weight_to_volume_conversion': 0.9},
        {'name': 'Bacon', 'category': 'Protein', 'weight_to_volume_conversion': 0.4},
        {'name': 'Lax', 'category': 'Protein', 'weight_to_volume_conversion': 1.0},
        {'name': 'Tofu', 'category': 'Protein', 'weight_to_volume_conversion': 1.0},
    ]

    for ingredient_data in ingredients_to_add:
        ingredient_data.setdefault('common_denonyms', [])
        ingredient_data.setdefault('weight_to_volume_conversion', 1.0)
        ManagedIngredient.objects.get_or_create(name=ingredient_data['name'], defaults=ingredient_data)

def reverse_preload(apps, schema_editor):
    ManagedIngredient = apps.get_model('recipes', 'ManagedIngredient')
    ingredient_names = [
        'Vetemjöl', 'Strösocker', 'Farinsocker', 'Bakpulver', 
        'Bikarbonat', 'Salt', 'Svartpeppar', 'Olivolja', 'Matolja', 
        'Pasta', 'Ris', 'Krossade tomater', 'Kycklingbuljong', 'Grönsaksbuljong',
        'Mjölk', 'Smör', 'Ägg', 'Riven cheddar', 'Mozzarella', 'Yoghurt',
        'Lök', 'Vitlök', 'Morötter', 'Selleri', 'Potatis', 'Tomater', 'Sallad',
        'Citron', 'Äpplen', 'Bananer', 'Kycklingfilé', 'Nötfärs', 'Bacon',
        'Lax', 'Tofu'
    ]
    ManagedIngredient.objects.filter(name__in=ingredient_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_managedingredient_category_and_more'),
    ]

    operations = [
        migrations.RunPython(preload_ingredients, reverse_code=reverse_preload),
    ]
