# Generated by Django 5.1.6 on 2025-07-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_preload_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedingredient',
            name='container_sizes',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('liter', 'liter'), ('dl', 'deciliter'), ('cl', 'centiliter'), ('ml', 'milliliter'), ('krm', 'kryddmått'), ('tsk', 'tesked'), ('msk', 'matsked'), ('st', 'styck')], max_length=50),
        ),
        migrations.AlterField(
            model_name='managedingredient',
            name='weight_to_volume_conversion',
            field=models.FloatField(default=1.0, help_text='Grams per milliliter (g/ml)'),
        ),
    ]
