# Generated by Django 5.1.6 on 2025-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_managedingredient_container_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('liter', 'liter'), ('dl', 'deciliter'), ('cl', 'centiliter'), ('ml', 'milliliter'), ('krm', 'kryddmått'), ('tsk', 'tesked'), ('msk', 'matsked'), ('st', 'styck'), ('nypa', 'nypa'), ('klyfta', 'klyfta')], max_length=50),
        ),
    ]
